services:
    laravel.test:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.3/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - redis
            - typesense
            - mailpit
    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    typesense:
        image: "typesense/typesense:0.25.2"
        ports:
            - "${FORWARD_TYPESENSE_PORT:-8108}:8108"
        environment:
            TYPESENSE_DATA_DIR: "${TYPESENSE_DATA_DIR:-/typesense-data}"
            TYPESENSE_API_KEY: "${TYPESENSE_API_KEY:-xyz}"
            TYPESENSE_ENABLE_CORS: "${TYPESENSE_ENABLE_CORS:-true}"
        volumes:
            - "sail-typesense:/typesense-data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - "--no-verbose"
                - "--spider"
                - "http://localhost:8108/health"
            retries: 5
            timeout: 7s
    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
        networks:
            - sail
    mongo:
        image: "mongo:latest"
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MDB_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MDB_PASSWORD}"
            MONGO_INITDB_DATABASE: "${MDB_DATABASE}"
        volumes:
            - "sailmongo:/data/mdb"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-typesense:
        driver: local
    sailmongo:
        driver: local
